export default defineEventHandler((event) => {
  const data = [
    {
      id: 1,
      name: "Novel 1",
      category: "Fiksi",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 1",
      rating: 4.5,
      synopsis: "Sinopsis Novel 1...",
      likes: 100,
      reads: 5000,
      episodes: 10,
      tags: "Romantis | Fantasi | Petualangan",
    },
    {
      id: 2,
      name: "Novel 2",
      category: "Fiksi Ilmiah",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 2",
      rating: 3.8,
      synopsis: "Sinopsis Novel 2...",
      likes: 75,
      reads: 3000,
      episodes: 12,
      tags: "Sains | Petualangan",
    },
    {
      id: 3,
      name: "Novel 3",
      category: "Romantis",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 3",
      rating: 4.0,
      synopsis: "Sinopsis Novel 3...",
      likes: 120,
      reads: 8000,
      episodes: 8,
      tags: "Romantis | Drama",
    },
    {
      id: 4,
      name: "Novel 4",
      category: "Fantasi",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 4",
      rating: 4.7,
      synopsis: "Sinopsis Novel 4...",
      likes: 90,
      reads: 6000,
      episodes: 15,
      tags: "Fantasi | Petualangan",
    },
    {
      id: 5,
      name: "Novel 5",
      category: "Drama",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 5",
      rating: 3.5,
      synopsis: "Sinopsis Novel 5...",
      likes: 60,
      reads: 4000,
      episodes: 9,
      tags: "Drama | Romantis",
    },
    {
      id: 6,
      name: "Novel 6",
      category: "Horor",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 6",
      rating: 4.2,
      synopsis: "Sinopsis Novel 6...",
      likes: 110,
      reads: 7000,
      episodes: 11,
      tags: "Horor | Misteri",
    },
    {
      id: 7,
      name: "Novel 7",
      category: "Petualangan",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 7",
      rating: 3.9,
      synopsis: "Sinopsis Novel 7...",
      likes: 85,
      reads: 5500,
      episodes: 14,
      tags: "Petualangan | Fantasi",
    },
    {
      id: 8,
      name: "Novel 8",
      category: "Komedi",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 8",
      rating: 4.3,
      synopsis: "Sinopsis Novel 8...",
      likes: 95,
      reads: 6500,
      episodes: 13,
      tags: "Komedi | Drama",
    },
    {
      id: 9,
      name: "Novel 9",
      category: "Misteri",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 9",
      rating: 3.7,
      synopsis: "Sinopsis Novel 9...",
      likes: 70,
      reads: 4500,
      episodes: 7,
      tags: "Misteri | Horor",
    },
    {
      id: 10,
      name: "Novel 10",
      category: "Roman",
      imageUrl: "https://via.placeholder.com/120x160",
      author: "Penulis 10",
      rating: 4.6,
      synopsis: "Sinopsis Novel 10...",
      likes: 105,
      reads: 7500,
      episodes: 16,
      tags: "Roman | Drama",
    },
  ];
  return data;
});
